serial:
  port: COM3
  baudrate: 115200
board:
  files: 8
  ranks: 8
  width_mm: 400.0
  height_mm: 400.0
  origin_x_mm: 0.0
  origin_y_mm: 0.0
  feedrate_mm_min: 2000
safety:
  max_speed_mm_min: 5000
  min_speed_mm_min: 100
  enable_speed_limit: true
machine:
  x_min: 0.0
  x_max: 400.0
  y_min: 0.0
  y_max: 415.0
  z_min: 0.0
  z_max: 100.0
profiles:
  active: Board with Perimeter Storage
  saved:
  - name: Standard Chess 400mm
    board:
      files: 8
      ranks: 8
      width_mm: 400.0
      height_mm: 400.0
      origin_x_mm: 0.0
      origin_y_mm: 0.0
      feedrate_mm_min: 2000
    pieces:
      king:
        height_mm: 85
        base_diameter_mm: 30
        grip_angle: 90
      queen:
        height_mm: 75
        base_diameter_mm: 28
        grip_angle: 85
      bishop:
        height_mm: 65
        base_diameter_mm: 26
        grip_angle: 80
      knight:
        height_mm: 55
        base_diameter_mm: 26
        grip_angle: 80
      rook:
        height_mm: 50
        base_diameter_mm: 26
        grip_angle: 75
      pawn:
        height_mm: 45
        base_diameter_mm: 24
        grip_angle: 70
  - name: 15.75 inch Board
    board:
      files: 8
      ranks: 8
      width_mm: 400.05
      height_mm: 400.05
      origin_x_mm: 0.0
      origin_y_mm: 0.0
      feedrate_mm_min: 2000
    pieces:
      king:
        height_mm: 95
        base_diameter_mm: 38
        grip_angle: 90
      queen:
        height_mm: 85
        base_diameter_mm: 35
        grip_angle: 85
      bishop:
        height_mm: 70
        base_diameter_mm: 32
        grip_angle: 80
      knight:
        height_mm: 60
        base_diameter_mm: 32
        grip_angle: 80
      rook:
        height_mm: 55
        base_diameter_mm: 32
        grip_angle: 75
      pawn:
        height_mm: 50
        base_diameter_mm: 28
        grip_angle: 70
  - name: Board with Top Storage
    board:
      files: 8
      ranks: 10
      width_mm: 400.0
      height_mm: 400.0
      origin_x_mm: 0.0
      origin_y_mm: 0.0
      feedrate_mm_min: 2000
      storage_layout: top
      play_area:
        min_file: 0
        max_file: 7
        min_rank: 0
        max_rank: 7
    pieces:
      king:
        height_mm: 85
        base_diameter_mm: 30
        grip_angle: 90
      queen:
        height_mm: 75
        base_diameter_mm: 28
        grip_angle: 85
      bishop:
        height_mm: 65
        base_diameter_mm: 26
        grip_angle: 80
      knight:
        height_mm: 55
        base_diameter_mm: 26
        grip_angle: 80
      rook:
        height_mm: 50
        base_diameter_mm: 26
        grip_angle: 75
      pawn:
        height_mm: 45
        base_diameter_mm: 24
        grip_angle: 70
  - name: Board with Perimeter Storage
    board:
      files: 10
      ranks: 10
      width_mm: 400.0
      height_mm: 400.0
      origin_x_mm: 0.0
      origin_y_mm: 0.0
      feedrate_mm_min: 2000
      storage_layout: perimeter
      play_area:
        min_file: 1
        max_file: 8
        min_rank: 1
        max_rank: 8
    pieces:
      king:
        height_mm: 75
        base_diameter_mm: 30
        grip_angle: 90
      queen:
        height_mm: 70
        base_diameter_mm: 28
        grip_angle: 85
      bishop:
        height_mm: 60
        base_diameter_mm: 26
        grip_angle: 80
      knight:
        height_mm: 55
        base_diameter_mm: 26
        grip_angle: 80
      rook:
        height_mm: 50
        base_diameter_mm: 26
        grip_angle: 75
      pawn:
        height_mm: 45
        base_diameter_mm: 24
        grip_angle: 70
